services:
  shift-hero-redis:
    container_name: ${DOCKER_REDIS_SERVICE_NAME}
    # restart: always
    image: redis:7.2.3-alpine
    ports:
      - "${REDIS_PORT}:${DOCKER_REDIS_PORT}"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      shift-hero-net:
        ipv4_address: 10.251.0.13
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  shift-hero-db:
    # should be the same as DB_HOST(hosting service)
    container_name: ${DOCKER_DB_SERVICE_NAME}
    # restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DOCKER_DB_PORT}"
    networks:
      shift-hero-net:
        ipv4_address: 10.251.0.12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 6

  shift-hero-api:
    container_name: ${DOCKER_API_SERVICE_NAME}
    image: ${DOCKER_API_SERVICE_NAME}:latest
    # restart: always
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.prod
    # entrypoint: ["${ENTRYPOINT_CMD}"]
    networks:
      shift-hero-net:
        ipv4_address: 10.251.0.11
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DOCKER_DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${DOCKER_REDIS_PORT}
      REDIS_INIT_DB: ${REDIS_INIT_DB}
      GIN_DOMAIN: ${GIN_DOMAIN}
      GIN_PORT: ${DOCKER_GIN_PORT}
      GIN_TRUSTED_PROXIES: ${GIN_TRUSTED_PROXIES}
      JWT_ACCESS_TOKEN_SECRET_KEY: ${JWT_ACCESS_TOKEN_SECRET_KEY}
      JWT_REFRESH_TOKEN_SECRET_KEY: ${JWT_REFRESH_TOKEN_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      APP_OFFICIAL_NAME: ${APP_OFFICIAL_NAME}
      APP_OFFICIAL_GMAIL: ${APP_OFFICIAL_GMAIL}
      APP_OFFICIAL_GOOGLE_PASSWORD: ${APP_OFFICIAL_GOOGLE_PASSWORD}
      APP_OFFICIAL_GOOGLE_APPLICATION_PASSWORD: ${APP_OFFICIAL_GOOGLE_APPLICATION_PASSWORD}
      ALLOWED_DOMAINS: ${ALLOWED_DOMAINS}
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GOOGLE_REDIRECT_URL: ${OAUTH_GOOGLE_REDIRECT_URL}
      OPEN_ROUTER_API_KEY: ${OPEN_ROUTER_API_KEY}
      OPEN_ROUTER_MODEL: ${OPEN_ROUTER_MODEL:-openai/gpt-oss-20b:free}
    expose:
      - "${DOCKER_GIN_PORT}"
    depends_on:
      shift-hero-db:
        condition: service_healthy
      shift-hero-redis:
        condition: service_healthy

  shift-hero-nginx:
    image: nginx:1.27-alpine
    container_name: ${DOCKER_NGINX_SERVICE_NAME}
    ports:
      - "${NGINX_HTTP_PORT}:${DOCKER_NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${DOCKER_NGINX_HTTPS_PORT}"
    networks:
      shift-hero-net:
        ipv4_address: 10.251.0.10
    volumes:
      - ./infra/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ${DOCKER_API_SERVICE_NAME}

networks:
  shift-hero-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.251.0.0/16

volumes:
  redis-data:
    name: shift-hero-redis-data
  # api-data:
  #   name: shift-hero-api-data
  postgres-data:
    name: shift-hero-postgres-data
