server:
  http_listen_port: ${DOCKER_TEMPO_PORT}

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:${DOCKER_OTEL_COLLECTOR_GRPC_PORT}
        http:
          endpoint: 0.0.0.0:${DOCKER_OTEL_COLLECTOR_HTTP_PORT}

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 72h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: local
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://${DOCKER_MIMIR_SERVICE_NAME}:9009/api/v1/push
        send_exemplars: true

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
